spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myweb?serverTimezone=JST
    username: docker
    password: docker

mybatis:
  config-location: classpath:/config/mybatis-config.xml